openapi: 3.0.1
info:
    title: Spark.SmartCharging.Api
    version: '1.0'
paths:
    /api/spot-prices/{priceArea}/advice/historic:
        get:
            tags:
                - GetHistoricSpotPricesAdvice
            operationId: GetHistoricSpotPricesAdvice
            parameters:
                - name: priceArea
                  in: path
                  required: true
                  style: simple
                  schema:
                      type: string
                - name: PreferredCurrency
                  in: query
                  style: form
                  schema:
                      type: string
                - name: EnergyPriceUnit
                  in: query
                  style: form
                  schema:
                      $ref: '#/components/schemas/EnergyUnit'
                - name: VATRate
                  in: query
                  style: form
                  schema:
                      type: number
                      format: double
                - name: ChargingRate
                  in: query
                  style: form
                  schema:
                      type: number
                      format: double
                - name: ChargingLength
                  in: query
                  style: form
                  schema:
                      type: integer
                      format: int32
                - name: StartFrom
                  in: query
                  style: form
                  schema:
                      type: string
                      format: date-time
            responses:
                '200':
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SpotPricesAdviceResponse'
    /api/forecast/{priceArea}:
        get:
            tags:
                - GetPriceForecast
            operationId: GetPriceForecast
            parameters:
                - name: priceArea
                  in: path
                  required: true
                  style: simple
                  schema:
                      type: string
                - name: PreferredCurrency
                  in: query
                  style: form
                  schema:
                      type: string
                - name: EnergyUnit
                  in: query
                  style: form
                  schema:
                      type: string
                - name: VATRate
                  in: query
                  style: form
                  schema:
                      type: number
                      format: double
                - name: ChargingPower
                  in: query
                  required: true
                  style: form
                  schema:
                      type: number
                      format: double
                - name: ChargingLength
                  in: query
                  required: true
                  style: form
                  schema:
                      type: integer
                      format: int32
            responses:
                '200':
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PriceForecastResponse'
    /api/spot-prices/{priceArea}:
        get:
            tags:
                - GetSpotPrices
            operationId: GetSpotPrices
            parameters:
                - name: priceArea
                  in: path
                  required: true
                  style: simple
                  schema:
                      type: string
                - name: PreferredCurrency
                  in: query
                  style: form
                  schema:
                      type: string
                - name: EnergyUnit
                  in: query
                  style: form
                  schema:
                      $ref: '#/components/schemas/EnergyUnit'
                - name: VATRate
                  in: query
                  style: form
                  schema:
                      type: number
                      format: double
            responses:
                '200':
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SpotPricesResponse'
    /api/spot-prices/{priceArea}/advice:
        get:
            tags:
                - GetSpotPricesAdvice
            operationId: GetSpotPricesAdvice
            parameters:
                - name: priceArea
                  in: path
                  required: true
                  style: simple
                  schema:
                      type: string
                - name: PreferredCurrency
                  in: query
                  style: form
                  schema:
                      type: string
                - name: EnergyPriceUnit
                  in: query
                  style: form
                  schema:
                      $ref: '#/components/schemas/EnergyUnit'
                - name: VATRate
                  in: query
                  style: form
                  schema:
                      type: number
                      format: double
                - name: ChargingRate
                  in: query
                  style: form
                  schema:
                      type: number
                      format: double
                - name: ChargingLength
                  in: query
                  style: form
                  schema:
                      type: integer
                      format: int32
                - name: StartFrom
                  in: query
                  style: form
                  schema:
                      type: string
                      format: date-time
            responses:
                '200':
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SpotPricesAdviceResponse'
components:
    schemas:
        AdviceSegmentType:
            enum:
                - Unknown
                - Now
                - Best
                - Good
                - Avoid
                - Worst
            type: string
        EnergyUnit:
            enum:
                - kWh
                - MWh
            type: string
        PriceForecastResponse:
            type: object
            properties:
                priceArea:
                    type: string
                    nullable: true
                currency:
                    type: string
                    nullable: true
                energyUnit:
                    $ref: '#/components/schemas/EnergyUnit'
                prices:
                    type: object
                    additionalProperties:
                        type: number
                        format: double
                    nullable: true
            additionalProperties: false
        SpotPriceAdviceSegment:
            type: object
            properties:
                from:
                    type: string
                    format: date-time
                to:
                    type: string
                    format: date-time
                type:
                    $ref: '#/components/schemas/AdviceSegmentType'
                cost:
                    type: number
                    format: double
                averagePrice:
                    type: number
                    format: double
            additionalProperties: false
        SpotPricesAdviceResponse:
            type: object
            properties:
                advice:
                    type: array
                    items:
                        $ref: '#/components/schemas/SpotPriceAdviceSegment'
                    nullable: true
                spotPrices:
                    type: array
                    items:
                        $ref: '#/components/schemas/SpotPricesEntry'
                    nullable: true
                priceArea:
                    type: string
                    nullable: true
                currency:
                    type: string
                    nullable: true
                energyUnit:
                    $ref: '#/components/schemas/EnergyUnit'
                pricesIncludingVAT:
                    type: boolean
                vatRate:
                    type: number
                    format: double
                    nullable: true
            additionalProperties: false
        SpotPricesEntry:
            type: object
            properties:
                time:
                    type: string
                    format: date-time
                price:
                    type: number
                    format: double
            additionalProperties: false
        SpotPricesResponse:
            type: object
            properties:
                priceArea:
                    type: string
                    nullable: true
                currency:
                    type: string
                    nullable: true
                energyUnit:
                    $ref: '#/components/schemas/EnergyUnit'
                pricesIncludingVAT:
                    type: boolean
                vatRate:
                    type: number
                    format: double
                    nullable: true
                prices:
                    type: object
                    additionalProperties:
                        type: number
                        format: double
                    nullable: true
            additionalProperties: false
