openapi: 3.0.0
info: 
  title: Spark API
  version: 1.0.0
  description: The Spark API is designed as a standard communication protocol between aggregators of smart energy devices and the Spark ecosystem. The Spark ecosystem can ingest one (or several) aggregators of smart energy devices. Smart energy devices are classified based on their nature of fascilitating enegy flexibilty. 
  contact: 
    name: Phillip Maree
    email: phillip.maree@volue.com
    url: https://www.volue.com/spark
servers: 
  - url: https://ev.dev-energy.volue.com
paths: 
  /ingest:
    post:
      summary: Ingest a smart energy device associated to a client ID.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                metadata:
                  $ref: '#/components/schemas/MetaData' 
                parameters:   
                  oneOf:
                    - $ref: '#/components/schemas/VechileParameters' 
                    - $ref: '#/components/schemas/ChargerParameters'
                    - $ref: '#/components/schemas/HVACParameters'
                    - $ref: '#/components/schemas/SolarInverterParameters'                 
      responses:
        '201':
          description: Ingested new resource 
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response'
                  
        '401':
          description: Duplicate ingestion of resource. Overwrite parameters 
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response'

  /update:
    put:
      summary: Update a smart energy device flexbility parameters.  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                metadata:
                  $ref: '#/components/schemas/MetaData'
                flexibility:
                  oneOf:
                    - $ref: '#/components/schemas/VehicleFlexibility'
                    - $ref: '#/components/schemas/ChargerFlexibility'
                    - $ref: '#/components/schemas/HVACFlexibility'
                    - $ref: '#/components/schemas/SolarInverterFlexibility'
      responses:
        '201':
          description: Smart energy device updated with flexbility parameters
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response'
                
        '401':
          description: No association for flexible resource  
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response'

components:
  schemas:
    
    Client:
      type: object
      properties:
        schema:
          type: string
          description: Client name 
        userId:
          type: string
          description: A version 4 UUID user id associated with client. 

    MetaData:
      type: object
      properties:
        client:
          $ref: '#/components/schemas/Client'
        device:
          $ref: '#/components/schemas/Device' 

    FlexibilityCatagory:
      type: string
      enum:
        - inflexible
        - shiftable
        - storage
        - adjustable
      description: >
        Flexibility categories according to EFI 2.0:
          * Inflexible - Cannot be controlled and has no actual flexibility, but is measurable and may provide forecasts (i.e., PV panels, domestic loads)
          * Shiftable - Process which can be shifted in time, e.g. has a deadline (i.e., white goods)
          * Storage - Flexible in production / consumption level, but is bounded by a buffer (i.e., CHP, EV)
          * Adjustable - Flexible in production / consumption level and not constrained by a buffer (i.e., heat pumps, gas boilers)
    
    DeviceClass:
      type: string
      enum:
        - vehicle
        - charger
        - inverter
        - hvac
    
    Device:
      type: object
      properties:
        catagory:
          $ref: '#/components/schemas/FlexibilityCatagory'
        class:
          $ref: '#/components/schemas/DeviceClass'
        assetId:
          type: string
          description: A version 4 UUID resource id. 
              
    VechileParameters:
      type: object
      properties:
        batteryCapacity:
          type: number
          description: Battery capacity measured in kW
        maximumStateOfCharge:
          type: number
          description: Maximum state of Charge in percentage of battery capacity measured in kW
        minimumStateOfCharge:
          type: number
          description: Minimum state of Charge in percentage of battery capacity measured in kW
    
    VehicleFlexibility:
      type: object
      properties:
        isActive:
          type: string
          description: Indicates if asset is availible for flexbility support 
          default: '0'
        latitude:
          type: number
          description: Latitude in Decimal Degrees (DD) format
          default: 63.446827
        longitude:
          type: number
          description: Longitude in Decimal Degrees (DD) format
          default: 10.421906
        arrivalTime:
          type: string
          description: ISO 8601 timestamp of last observed state
          default: '1970-01-01 00:00:00.000'
        departureTime:
          type: string
          description: ISO 8601 timestamp of expected departure
          default: '1970-01-01 00:00:00.000'
        stateOfCharge:
          type: number
          description: State of charge in percentage of battery capacity
          default: 0
        desirableStateOfCharge:
          type: number
          description: Desriable state of charge in percentage of battery capacity at time of departure
          default: 0
        chargeRate: 
          type: number
          description: Maximum charge rate of vehicle in kWh  
          default: 0
          
    ChargerParameters:
      type: object
      properties:
        mode:
          $ref: '#/components/schemas/ChargerModes'
        ratedPower:
          type: number
          description: Rated Power of charger in kW
        chargingRange:
          type: string
          description: Range of charging current in ampere

    ChargerFlexibility:
      type: object
      properties:
        isActive:
          type: string
          description: Indicates if asset is availible for flexbility support
          default: '0'
        latitude:
          type: number
          description: Latitude in Decimal Degrees (DD) format
          default: 63.446827
        longitude:
          type: number
          description: Longitude in Decimal Degrees (DD) format
          default: 10.421906
        chargeRate:
          type: number
          description: The current charge rate in kW
          default: 0
        maxCurrent:
          type: number
          description: Desired max current in ampere, if set
          default: 0
    
    HVACParameters:
      type: object

    HVACFlexibility:
      type: object
    
    SolarInverterParameters:
      type: object

    SolarInverterFlexibility:
      type: object

    ChargerModes:
      type: string
      enum:
        - Mode1 
        - Mode2
        - Mode3
        - Mode4
      description: >
        IEC 61851-1 Electric vehicle conductive charging system:
          * Mode1 - Standard socket outlet - domestic installation (2.3 kW AC)
          * Mode2 - Standard socket outlet with an AC EV supply equipment– domestic (2.3 kW AC)
          * Mode3 - AC EV equipment permanently connected to an AC supply network (3.7-22 kW AC)
          * Mode4 - DC EV Supply equipment ( 22-350 kW DC / 50 kW AC)    
    
    Response:
      type: object
      properties:
        status:
          type: string
          description: Status of executed command
          enum:
            - SUCCESS
            - FAILED
        summary:
          type: string
          description: Brief summary on status of executed task
        metadata:
          type: object
          description: Detailed response data as returned from executing a query
          properties:
            code:
              type: string
              description: Interal code descriptor for request execution
            body:
              type: string
              description: Metadata summary for debugging
            headers:
              type: string

            

        

        

        
      

